# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 314c1729cf84746e81e7ae1204b82a60bd228cbe580fb27f1c86545ca85a645b8c4519284fbe2b76af20c2d62ac75b0b06b1d0b75dd5fb4bf0c070c0373e02b7

test:
  secret_key_base: d34b1c8b0b037695e9f4a4ea0a1a47fe9ec76ec18ae0caf43ef14edc75b7ad8ceef8d6985aa0c225619fc337fff9898110bbed90b808df25cb892dd1a2fc3c34

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
